spring:
  application:
    name: resilience4j

management:
  endpoints:
    web:
      exposure:
        exclude: all
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

  resilience4j:
    circuitbreaker:
      instances:
        ExternalServiceImpl:
          failure-rate-threshold: 50
          minimum-number-of-calls: 5
          automatic-transition-from-open-to-half-open-enabled: true
          wait-duration-in-open-state: 5s
          permitted-number-of-calls-in-half-open-state: 3
          sliding-window-size: 10
          sliding-window-type: count_based

external:
  service:
    #url: https://www.google.com
    url: https://www.test-cicuitbraker.fallback